
import type { Metadata } from "next";

import "./globals.css";
import { EdgeStoreProvider } from "@/lib/edgestore";




export const metadata: Metadata = {
  title: "BookItNow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
      >


        <EdgeStoreProvider>{children}</EdgeStoreProvider>
      </body>
    </html>
  );
}
